using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApi_SY.Models
{
    public class sli_intpo_Import  //excle导入intpo
    {
        [Key]
        public int Id { get; set; }  // 假设存在一个自增的主键 Id，如果实际情况不需要，可删除此行

        public string my_document_no { get; set; }
        public string case_name { get; set; }
        public string case_status { get; set; }
        public string case_type { get; set; }
        public string customer_document_no { get; set; }
        public string customer_name { get; set; }
        public string customer_no { get; set; }
        public string product_type { get; set; }
        public string case_user { get; set; }
        public string date_apply { get; set; }
        public string date_submit { get; set; }
        public string is_date_submit { get; set; }
        public string is_publish { get; set; }
        public string is_reduce { get; set; }
        public string is_first { get; set; }
        public string is_das { get; set; }
        public string is_preview { get; set; }
        public string is_fast_case { get; set; }
        public string business_user { get; set; }
        public string business_deputy { get; set; }
        public string business_deptment { get; set; }
        public string open_date { get; set; }
        public string commission_case { get; set; }
        public string area { get; set; }
        public string receipt { get; set; }
        public string contract_no { get; set; }
        public string case_customer_user { get; set; }
        public string case_user_phone { get; set; }
        public string case_user_email { get; set; }
        public string assist_house_no { get; set; }
        public string register_no { get; set; }
        public string brand_category { get; set; }
        public string case_handle_dept { get; set; }
        public string belong_branch { get; set; }
        public string work_type { get; set; }
        public string case_direction { get; set; }
        public string case_user_deptment { get; set; }
        public string apply_tpye { get; set; }
        public string apply_no { get; set; }
        public string apply_date { get; set; }
        public string registration_no { get; set; }
        public string announcement_date { get; set; }
        public string new_submit_date { get; set; }
        public string case_remark { get; set; }
        public string is_advance { get; set; }
        public string reduce_proportion { get; set; }
        public string pay_no { get; set; }
        public string pct_apply_no { get; set; }
        public string pct_apply_date { get; set; }
        public string priority_date { get; set; }
        public string customer_category { get; set; }
        public string handle_event { get; set; }
        public string handle_event_stage { get; set; }
        public string handle_event_user { get; set; }
        public string handle_event_deptment { get; set; }
        public string event_remark { get; set; }
        public string handle_event_date { get; set; }
        public string first_draft_date { get; set; }
        public string inside_draft_date { get; set; }
        public string return_draft_date { get; set; }
        public string draft_date { get; set; }
        public string give_cooperate_date { get; set; }
        public string submit_date { get; set; }
        public string handle_event_status { get; set; }
        public string official_date { get; set; }
        public string inside_draft_date_two { get; set; }
        public string customer_date { get; set; }
        public string apply_user { get; set; }
        public string agent_mechanism { get; set; }
        public string invention_user { get; set; }
        public string money_type { get; set; }
        public string money_name { get; set; }
        public string money_description { get; set; }
        public string money_english { get; set; }
        public string price { get; set; }
        public string currency { get; set; }
        public string change_currency { get; set; }
        public string change_money { get; set; }
        public string receivable_date { get; set; }
        public string request_date { get; set; }
        public string actual_date { get; set; }
        public string actual_get_money { get; set; }
        public string actual_currency { get; set; }
        public string pay_date { get; set; }
        public string pay_head { get; set; }
        public string actual_pay_date { get; set; }
        public string request_money_no { get; set; }
        public string pay_year_stage { get; set; }
        public string pay_type { get; set; }
        public string exchange_rate { get; set; }
        public string money_remark { get; set; }
        public string update_record { get; set; }
        public string collection_account { get; set; }
        public string bill_no { get; set; }
        public string money_create_date { get; set; }
        public string invoice_no { get; set; }
        public string create_invoice_date { get; set; }
        public string cost_agent { get; set; }
        public string collection_status { get; set; }
        public string pay_status { get; set; }
        public string out_account_date { get; set; }
        public string power_ask_num { get; set; }
        public string instructions_num { get; set; }
        public string technical_field { get; set; }
        public string outside_user { get; set; }
        public string inside_user { get; set; }
        public string patent_label { get; set; }
        public string proposal_no { get; set; }
        public string proxy_user { get; set; }
        public string custom_one { get; set; }
        public string custom_two { get; set; }
        public string custom_three { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public string text3 { get; set; }
        public string text4 { get; set; }
        public string text5 { get; set; }
        public string text6 { get; set; }
        public string text7 { get; set; }
        public string text8 { get; set; }
        public string text9 { get; set; }
        public string text10 { get; set; }
        public string text11 { get; set; }
        public string text12 { get; set; }
        public string text13 { get; set; }
        public string text14 { get; set; }
        public string text15 { get; set; }
        public string text16 { get; set; }
        public string text17 { get; set; }
        public string text18 { get; set; }
        public string text19 { get; set; }
        public string text20 { get; set; }
        public string bill_no_date { get; set; }
        public int keeding_status { get; set; }
        public string keeding_reason { get; set; }
        public int keeding_flag { get; set; }
        public string keeding_fsync_date { get; set; }
        public string case_user_no { get; set; }
        public string business_deptment_no { get; set; }
        public string handle_event_deptment_no { get; set; }
        public string my_document_no_no { get; set; }
        public string business_user_no { get; set; }
        public string handle_event_user_no { get; set; }
        public string text21 { get; set; }
        public string text22 { get; set; }
        public string text23 { get; set; }
        public string text24 { get; set; }
        public string text25 { get; set; }
        public string text26 { get; set; }
        public string text27 { get; set; }
        public string text28 { get; set; }
        public string text29 { get; set; }
        public string text30 { get; set; }
        public string text31 { get; set; }
        public string text32 { get; set; }
        public string text33 { get; set; }
        public string text34 { get; set; }
        public string text35 { get; set; }
        public string text36 { get; set; }
        public string text37 { get; set; }
        public string text38 { get; set; }
        public string text39 { get; set; }
        public string text40 { get; set; }
    }
}